### ISSUE TITLE
Unable to Compile using Dafny 3 // Ubuntu 20 // DotNet 3.1.405

### ISSUE THREAD

**Issue by thiagomata** [DafnyVSCode/ide-vscode#16] opened 2021-01-28 12:00 UTC
Command 'Dafny: Compile' resulted in an error (command 'dafny.compile' not found)

![image](https://user-images.githubusercontent.com/581320/106135692-1dfd0880-611d-11eb-9727-381d97ffedc4.png)

```
dafny@ubuntu:~/Documents$ dotnet --version
3.1.405
```
```
dafny@ubuntu:~/Documents$ dafny /compile 1 test.dfy 
/home/dafny/Documents/test.dfy(2,13): Error: assertion violation
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 0 verified, 1 error
```
```
# test.dfy
method Main() {
    assert 1 == 3;
}
```
```
$ whereis dotnet
dotnet: /usr/bin/dotnet /usr/local/bin/dotnet /usr/share/dotnet /snap/bin/dotnet
```
```
$ whereis dafny
dafny: /usr/bin/dafny /usr/share/man/man1/dafny.1.gz
```

```
$ ls /usr/lib/dafny3/Dafny*
/usr/lib/dafny3/Dafny.deps.json    /usr/lib/dafny3/DafnyPipeline.pdb         /usr/lib/dafny3/DafnyRuntime.go   /usr/lib/dafny3/DafnyServer.deps.json
/usr/lib/dafny3/Dafny.dll          /usr/lib/dafny3/DafnyPrelude.bpl          /usr/lib/dafny3/DafnyRuntime.jar  /usr/lib/dafny3/DafnyServer.dll
/usr/lib/dafny3/Dafny.dll.config   /usr/lib/dafny3/Dafny.runtimeconfig.json  /usr/lib/dafny3/DafnyRuntime.js   /usr/lib/dafny3/DafnyServer.dll.config
/usr/lib/dafny3/Dafny.pdb          /usr/lib/dafny3/DafnyRuntime.cs           /usr/lib/dafny3/DafnyRuntime.pdb  /usr/lib/dafny3/DafnyServer.pdb
/usr/lib/dafny3/DafnyPipeline.dll  /usr/lib/dafny3/DafnyRuntime.dll          /usr/lib/dafny3/DafnyServer       /usr/lib/dafny3/DafnyServer.runtimeconfig.json
```

**Comment by camrein** [comment] 2021-01-28 12:25
I see one problematic configuration: "Language Server Runtime Path" (hint: the erroneous assertion should be marked in the editor). This plugin no longer uses the "Dafny Server" distributed with Dafny itself. It requires a standardized language server that is distributed separately: https://github.com/dafny-lang/language-server-csharp/releases/tag/v2.3.0
Side-note: If you leave this configuration empty, the plugin should automatically download the correct version (including a compatible Dafny compiler).

Coming back to your issue. I guessed that the old Dafny-Server distro somehow prevents the plugin from fully registering upon launch; thus, you have an unregistered command. A quick shot confirmed my guess. So I believe using the correct language server should fix your problems.

**Comment by camrein** [comment] 2021-02-19 14:23
I assume that the issue is resolved and close the issue.

**Closed by camrein** 2021-02-19 14:23 UTC
