### ISSUE TITLE
Requesting counterexample generates Internal Error

### ISSUE THREAD

**Issue by hmijail** [DafnyVSCode/ide-vscode#25] opened 2021-03-12 06:48 UTC
correctnesslab.dafny-vscode 1.4.0
VSCode versions: 
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:09.783Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

When requesting a counterexample, an Internal Error is shown in VSCode.

Code: 
```
method test(a: seq<int>) returns (b: seq<int>)
    ensures |a| >= |b|
{
  return b;
}
```

Error:
```
CounterExample request failed: Internal Error - System.ArgumentException: state does not contain position: bug_counterexample.d..(4,0):initial state at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.CounterExampleLoader.GetPositionFromInitialState(IState state) in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 97 at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.CounterExampleLoader.GetCounterExample(StateNode state) in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 90 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items) at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items) at System.Linq.Enumerable.SelectManySingleSelectorIt...
```

**Comment by hmijail** [comment] 2021-03-12 06:48
In case it helps: before I reduced the bug-triggering code, the error reported was different:
```
CounterExample request failed: Internal Error - System.ArgumentException: function 'Seq#Index' previously created with arity 1, now trying to recreate with arity 2 at Microsoft.Boogie.Model.MkFunc(String name, Int32 arity) at Microsoft.Boogie.ModelViewer.Dafny.DafnyModel..ctor(Model m, ViewOptions opts) in /Users/runner/work/language-server-csharp/language-server-csharp/dafny/Source/DafnyServer/boogie/DafnyProvider.cs:line 45 at Microsoft.Boogie.ModelViewer.Dafny.Provider.GetLanguageSpecificModel(Model m, ViewOptions opts) in /Users/runner/work/language-server-csharp/language-server-csharp/dafny/Source/DafnyServer/boogie/DafnyProvider.cs:line 25 at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.CounterExampleLoader.GetLanguagSpecificModel(Model model) in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 74 at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNe...
```

**Comment by camrein** [comment] 2021-03-12 08:03
Thanks for your report. Your initial gut feeling was right: It appears to be more an issue of the language server than the extension.
However, I am unable to reproduce this error. For me, it works for both Ubuntu 20.40 and Windows 10 installations.
![grafik](https://user-images.githubusercontent.com/18049310/110908988-d8348200-830f-11eb-964d-3680587e590d.png)

I have a strong feeling that this is an issue related to the OS. 

Could you please check the log file located here (unless you have changed the installation dir of the language server or vscode extensions):
```bash
~/.vscode/extensions/correctnesslab.dafny-vscode-1.4.0/out/dafnyLanguageServer/log.text
```

I think the best is to first clear/remove the log file and then try to reproduce your error. Then we should have a rather minimal log file that might give a better indication of the root cause (and not a truncated version as we have in the terminal output).

Last but not least: Does the automatic verification work as expected?

**Comment by hmijail** [comment] 2021-03-14 12:52
I removed the log.txt file and requested the counterexample. Resulting log follows:
```
2021-03-14 22:48:52.4911|FATAL|OmniSharp.Extensions.JsonRpc.InputHandler|Failed to handle request dafny/counterExample 8 System.ArgumentException: state does not contain position: bug_counterexample.d..(4,0):initial state
   at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.CounterExampleLoader.GetPositionFromInitialState(IState state) in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 99
   at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.CounterExampleLoader.GetCounterExample(StateNode state) in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 90
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.CounterExampleLoader.GetCounterExamples() in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 58
   at Microsoft.Dafny.LanguageServer.Handlers.Custom.DafnyCounterExampleHandler.Handle(CounterExampleParams request, CancellationToken cancellationToken) in /Users/runner/work/language-server-csharp/language-server-csharp/Source/DafnyLS/Handlers/Custom/DafnyCounterExampleHandler.cs:line 33
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()

```

> Does the automatic verification work as expected?  

I'm a beginner at Dafny, but yes, it seems to work as expected when following various tutorials.

**Comment by camrein** [comment] 2021-03-15 08:21
I am closing this issue in favor of dafny-lang/language-server-csharp/issues/49.

**Closed by camrein** 2021-03-15 08:21 UTC
